/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class smtown_ai_karaokescore_KaraokeScore */

#ifndef _Included_smtown_ai_karaokescore_KaraokeScore
#define _Included_smtown_ai_karaokescore_KaraokeScore
#ifdef __cplusplus
extern "C" {
#endif
#undef smtown_ai_karaokescore_KaraokeScore_DEFAULT_SAMPLE_RATE
#define smtown_ai_karaokescore_KaraokeScore_DEFAULT_SAMPLE_RATE 44100L
#undef smtown_ai_karaokescore_KaraokeScore_DEFAULT_FRAME_SIZE
#define smtown_ai_karaokescore_KaraokeScore_DEFAULT_FRAME_SIZE 2048L
#undef smtown_ai_karaokescore_KaraokeScore_DEFAULT_HOP_SIZE_IN_MS
#define smtown_ai_karaokescore_KaraokeScore_DEFAULT_HOP_SIZE_IN_MS 50L
#undef smtown_ai_karaokescore_KaraokeScore_STATE_RELEASED
#define smtown_ai_karaokescore_KaraokeScore_STATE_RELEASED 0L
#undef smtown_ai_karaokescore_KaraokeScore_STATE_INITED
#define smtown_ai_karaokescore_KaraokeScore_STATE_INITED 1L
/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    getScoreInstanceID
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_smtown_ai_karaokescore_KaraokeScore_getScoreInstanceID
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    readFilesNative
 * Signature: (ILjava/lang/String;[Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_smtown_ai_karaokescore_KaraokeScore_readFilesNative
  (JNIEnv *, jobject, jint, jstring, jobjectArray, jstring);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    getPitchArrayLengthNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_smtown_ai_karaokescore_KaraokeScore_getPitchArrayLengthNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    getPitchArraiesNative
 * Signature: (I[F[F)V
 */
JNIEXPORT void JNICALL Java_smtown_ai_karaokescore_KaraokeScore_getPitchArraiesNative
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    getPartCountNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_smtown_ai_karaokescore_KaraokeScore_getPartCountNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    getScoreNative
 * Signature: (IIFFFIII)F
 */
JNIEXPORT jfloat JNICALL Java_smtown_ai_karaokescore_KaraokeScore_getScoreNative
  (JNIEnv *, jobject, jint, jint, jfloat, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    releaseNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_smtown_ai_karaokescore_KaraokeScore_releaseNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    getAudioBufferLength
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_smtown_ai_karaokescore_KaraokeScore_getAudioBufferLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     smtown_ai_karaokescore_KaraokeScore
 * Method:    getAudioBuffer
 * Signature: (I[S)V
 */
JNIEXPORT void JNICALL Java_smtown_ai_karaokescore_KaraokeScore_getAudioBuffer
  (JNIEnv *, jobject, jint, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
